--表空间
CREATE SMALLFILE 
    TABLESPACE "UPSYS_DATA" 
    LOGGING 
    DATAFILE 'D:\APP\ADMINISTRATOR\ORADATA\ORCL\UPSYS_DATA.ora' SIZE
    8000M AUTOEXTEND 
    ON NEXT  80M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT  AUTO ;
CREATE SMALLFILE 
    TABLESPACE "IMS_DATA" 
    LOGGING 
    DATAFILE 'D:\APP\ADMINISTRATOR\ORADATA\ORCL\IMS_DATA.ora' SIZE
    8000M AUTOEXTEND 
    ON NEXT  80M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT  AUTO ;
--用户 注意密码改了：upsys_aerothinker
CREATE USER "UPSYS"  PROFILE "DEFAULT" 
    IDENTIFIED BY "upsys_aerothinker" DEFAULT TABLESPACE "UPSYS_DATA" 
    TEMPORARY TABLESPACE "TEMP" 
    ACCOUNT UNLOCK;
GRANT "CONNECT" TO "UPSYS";
GRANT "DBA" TO "UPSYS";

CREATE USER "IMS"  PROFILE "DEFAULT" 
    IDENTIFIED BY "upsys_aerothinker" DEFAULT TABLESPACE "IMS_DATA" 
    TEMPORARY TABLESPACE "TEMP" 
    ACCOUNT UNLOCK;
GRANT "CONNECT" TO "IMS";
GRANT "DBA" TO "IMS";

--调整临时表空间大小
ALTER DATABASE TEMPFILE 
    'D:\APP\ADMINISTRATOR\ORADATA\ORCL\TEMP01.DBF' RESIZE  8000M;
ALTER DATABASE TEMPFILE 'D:\APP\ADMINISTRATOR\ORADATA\ORCL\TEMP01.DBF' AUTOEXTEND ON NEXT  80M MAXSIZE UNLIMITED;
--
ALTER DATABASE 
    DATAFILE 'D:\APP\ADMINISTRATOR\ORADATA\ORCL\SYSAUX01.DBF' 
    RESIZE  2000M;
ALTER DATABASE DATAFILE 'D:\APP\ADMINISTRATOR\ORADATA\ORCL\SYSAUX01.DBF' AUTOEXTEND ON NEXT  20M;
--调整undo表空间
ALTER DATABASE 
    DATAFILE 'D:\APP\ADMINISTRATOR\ORADATA\ORCL\UNDOTBS01.DBF' 
    RESIZE  4000M;
ALTER DATABASE DATAFILE 'D:\APP\ADMINISTRATOR\ORADATA\ORCL\UNDOTBS01.DBF' AUTOEXTEND ON NEXT  80M;
--调整system表空间
ALTER DATABASE 
    DATAFILE 'D:\APP\ADMINISTRATOR\ORADATA\ORCL\SYSTEM01.DBF' 
    RESIZE  1000M;
ALTER DATABASE DATAFILE 'D:\APP\ADMINISTRATOR\ORADATA\ORCL\SYSTEM01.DBF' AUTOEXTEND ON NEXT  30M;

